[project]
name = "octopus"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "exchangelib>=5.5.1",
    "pydantic-settings>=2.9.1",
    "requests>=2.32.3",
]
